version: "3.11.2"

services:
  redis:
    image: 'redis:slim'

  web:
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8100:8080"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./_static:/app/_static
    env_file:
      - .env

volumes:
  static_volume:
  media_volume: