# Generated by Django 5.0.6 on 2024-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chama_balance_useraccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='chama_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
