# Generated by Django 5.0.6 on 2024-07-03 05:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='chama_name',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='chama',
            name='chama_account',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chama',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
