# Generated by Django 5.0.6 on 2024-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_chama_chama_name_remove_chama_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chama',
        ),
        migrations.AddField(
            model_name='chama',
            name='chama_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='chama',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chama',
            name='chama_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chama',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='chama',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(),
        ),
    ]
