# Generated by Django 5.0.6 on 2024-07-03 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_user_chama_chama_chama_id_user_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
            ],
        ),
    ]
